workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS App
        script: |
          xcodebuild build \
            -project SocialFeedApp.xcodeproj \
            -scheme SocialFeedApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
